version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: epic_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: click123
      POSTGRES_DB: epic_poc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: